# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ving Tsun Austria
email: dietmar.christl@vingstun.at
phone: +43 1 947 91 12
description: > # this means to ignore newlines until "baseurl:"
  Ving Tsun Kung Fu Association Europe
# url: "https://vingtsun.github.io" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://vingtsunaustria.at" # the base hostname & protocol for your site, e.g. http://example.com
repository: "vingtsun/vingtsun.github.io"

htmllang: "de-at"

# Global configuration
#source: "src/jekyll"
#destination: "dist"
include: []
exclude: [
  ".gitignore",
  #"node_modules",
  "LICENSE",
  #"package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock",
  #"gulpfile.babel.js",
  #".babelrc",
  #"src",
  #"validate"
]
keep_files: [
  #"static",
]
#defaults:
  #- scope:
      #path: "static/images"
    #values:
      #image: true

# More Configuration
collections:
  - articles
  - sections
  - schulen
#sass:
  #css_location: "../css/"
  #style: compressed

# Build command options
future: true
#profile: true 

# Conversion
markdown: kramdown

# Serving
baseurl: "" # the subpath of your site, e.g. /blog

# Outputting
permalink: pretty


